#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
void IRQ_Setting();
void Potentiometer_Read();
void ADC_Read_and_Convert(void);
void GPT0_Setting();
void GPT3_Setting();
void Rotate_Servo();
void Cds_Sensor_Read();
void Calc_Degree();
void Thermal_Sensor_Read();
void Increase_Motor();
void Decrease_Motor();
void Stop_Motor();
void Set_Motor_Speed();
FSP_CPP_FOOTER

volatile uint8_t Accelerator =0;
volatile uint8_t Brake=0;

/*  SERVO  */
const double SERVO_MINIMUM_DUTY = 0.03;
const double SERVO_MAXIMUM_DUTY = 0.12;
const double SERVO_EACH_DEGREE = (SERVO_MAXIMUM_DUTY - SERVO_MINIMUM_DUTY) / 180;

double temp_calc = 0.0;
uint8_t degree = 0;

/*  DC  */
bsp_io_port_pin_t L293_CH0_Enable = BSP_IO_PORT_09_PIN_00;
bsp_io_port_pin_t L293_CH0_Direction = BSP_IO_PORT_09_PIN_01;
uint8_t L293_CH0_Enable_Level = BSP_IO_LEVEL_LOW;
uint8_t L293_CH0_Direction_Level = BSP_IO_LEVEL_HIGH;
uint32_t Timer_Period = 0x249F00; // 20[ms] Duty Cycle (50[Hz])

uint32_t dutyRate = 0;

int motor_speed = 0;  // current speed
const int max_speed = 100;  // maximum speed
const int min_speed = 0;  // minimum speed

const uint8_t AGT_CHANNEL = 0;

uint16_t potentiometer_mV = 0, potentiometer_Ra = 0, potentiometer_Rb = 0;
uint16_t potent_max = 1000;
uint16_t potent_min = 0;
uint16_t temperature_mV; int16_t temperature;
uint16_t cds_data;
typedef enum {
    CDS_light = 0,
    CDS_dark = 1,
}CDS_t;

CDS_t brightness;

uint32_t i = 0;

uint16_t SampleSpeed = 5;

double Duty_count=0;

const float ADC_CONST = (float)(3.3/4096);


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    IRQ_Setting();

    /* ADC init */
    R_ADC_Open(&g_adc0_ctrl, &g_adc0_cfg);
    R_ADC_ScanCfg(&g_adc0_ctrl, &g_adc0_channel_cfg);

    GPT0_Setting();
    GPT3_Setting();

    R_GPT0->GTCR_b.CST = 1U; // GPT32EH0 Count Start
    R_GPT3->GTCR_b.CST = 1U; // GPT32EH3 Count Start

    L293_CH0_Enable_Level = 0x01;
    R_IOPORT_PinWrite(&g_ioport_ctrl, L293_CH0_Enable, L293_CH0_Enable_Level);

    L293_CH0_Direction_Level = 0x01;
    R_IOPORT_PinWrite(&g_ioport_ctrl, L293_CH0_Direction, L293_CH0_Direction_Level);
	
    /* TODO: add your own code here */
    while(1){

        ADC_Read_and_Convert();
        Calc_Degree();


        if(Accelerator == 1)
        {
            Increase_Motor();
        }

        if(Brake == 1)
        {
            Decrease_Motor();
        }

        if(brightness == 1)
        {
            Stop_Motor();
        }
    }
}

/* TODO: add your own code here */

void Increase_Motor()
{
    if(motor_speed < max_speed) {
           motor_speed += 10;
           R_BSP_SoftwareDelay(500000, BSP_DELAY_UNITS_MICROSECONDS);
           Set_Motor_Speed(motor_speed);
       }
    else {
        Set_Motor_Speed(100);
    }
}

void Decrease_Motor()
{
    if(motor_speed > min_speed) {
            motor_speed -= 10;
            R_BSP_SoftwareDelay(500000, BSP_DELAY_UNITS_MICROSECONDS);
            Set_Motor_Speed(motor_speed);
        }
    else {
            Set_Motor_Speed(0);
    }
}

void Stop_Motor()
{
    motor_speed = 0;
    Set_Motor_Speed(motor_speed);
}

void Set_Motor_Speed(int speed) {
    if (speed < 0)
    {
        speed = 0;
    }
    else if (speed > 100)
    {
        speed = 100;
    }

    dutyRate = Timer_Period * (100 - speed) / 100;

    R_GPT3->GTCCR[0] = dutyRate;
}

void Calc_Degree()
{
    {
        degree = (uint8_t)(180 * (float)potentiometer_Ra / 10000);

        Rotate_Servo();
    }
}

void Rotate_Servo()
{
    temp_calc = (SERVO_MINIMUM_DUTY + SERVO_EACH_DEGREE * (float)degree);

    R_GPT0->GTCCR[0] = (uint32_t)(Timer_Period * temp_calc);
}

void Potentiometer_Read()
{
    uint16_t ch0_adc_result;

    R_ADC_Read(&g_adc0_ctrl, ADC_CHANNEL_0, &ch0_adc_result);
    potentiometer_mV = (uint16_t)(ch0_adc_result * ADC_CONST * 1000);
    potentiometer_Rb = (uint16_t)(potentiometer_mV * 3.0303);
    potentiometer_Ra = (uint16_t)(10000 - potentiometer_Rb);
}

void Cds_Sensor_Read()
{
    uint16_t ch2_adc_result;

    R_ADC_Read(&g_adc0_ctrl, ADC_CHANNEL_2, &ch2_adc_result);
    if(ch2_adc_result >= 400){
        cds_data = ch2_adc_result;
        brightness = CDS_dark;
    }
    else{
        cds_data = ch2_adc_result;
        brightness = CDS_light;
    }
}

void ADC_Read_and_Convert(void)
{
    adc_status_t status;

    R_ADC_ScanStart(&g_adc0_ctrl);
    status.state = ADC_STATE_SCAN_IN_PROGRESS;
    while(ADC_STATE_SCAN_IN_PROGRESS == status.state){
        R_ADC_StatusGet(&g_adc0_ctrl, &status);
    }

    Potentiometer_Read();
    Cds_Sensor_Read();
}

void IRQ_Setting(){
    R_ICU_ExternalIrqOpen(&g_external_irq11_ctrl, &g_external_irq11_cfg);
    R_ICU_ExternalIrqEnable(&g_external_irq11_ctrl);
    R_ICU_ExternalIrqOpen(&g_external_irq12_ctrl, &g_external_irq12_cfg);
    R_ICU_ExternalIrqEnable(&g_external_irq12_ctrl);

    R_ICU->IRQCR[11] |= 0x2; // both edge mode
    R_ICU->IRQCR[12] |= 0x2; // both edge mode
}

void GPT0_Setting()
{
    R_MSTP->MSTPCRD_b.MSTPD5 = 0U; // GPT32EH0 Module Stop State Cancel

    R_GPT0->GTCR_b.MD = 0U; // GPT32EH0 Count Mode Setting (Saw-wave PWM Mode)
    R_GPT0->GTCR_b.TPCS = 0U; // GPT32EH0 Clock Source Pre-scale Setting (PCLKD/1)

    R_GPT0->GTPR = Timer_Period - 1; // GPT32EH0 Counting Maximum Cycle Setting
    R_GPT0->GTCNT = 0; // GPT32EH0 Counter Initial Value Setting

    R_GPT0->GTIOR_b.GTIOA = 9U; // Compare Matching Output Control Setting
    R_GPT0->GTIOR_b.OAE = 1U; // GPIOCA Output Pin Enable

    R_GPT0->GTCCR[0] = (uint32_t)(Timer_Period * SERVO_MINIMUM_DUTY); // GTCCR Initial Setting (Angle = 0[degree])
}

void GPT3_Setting()
{
    R_MSTP->MSTPCRD_b.MSTPD5 = 0U; // GPT32EH3 Module Stop State Cancel

    R_GPT3->GTCR_b.MD = 0U; // GPT32EH3 Count Mode Setting (Saw-wave PWM Mode)
    R_GPT3->GTCR_b.TPCS = 0U; // GPT32EH3 Clock Source Pre-scale Setting (PCLKD/1)

    R_GPT3->GTPR = Timer_Period - 1; // GPT32EH3 Counting Maximum Cycle Setting
    R_GPT3->GTCNT = 0; // GPT32EH3 Counter Initial Value Setting

    R_GPT3->GTIOR_b.GTIOA = 9U; // Compare Matching Output Control Setting
    R_GPT3->GTIOR_b.OAE = 1U; // GPIOCA Output Pin Enable
}

void R_IRQ_Callback(external_irq_callback_args_t *p_args)
{
    uint32_t switch_channel;
    switch_channel = p_args -> channel;
    if (switch_channel == 11){
        Accelerator ^= 0x1;
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_10_PIN_08, !Accelerator);

    }
    else if (switch_channel == 12){
        Brake ^= 0x1;
        R_IOPORT_PinWrite(&g_ioport_ctrl, BSP_IO_PORT_10_PIN_09, !Brake);
    }
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
