#include "hal_data.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
void Initial_Setting();
void R_FND_Reset();
void R_FND_Print_Data(uint8_t *string);
void R_FND_Display_Data(uint8_t digit, uint8_t data);
FSP_CPP_FOOTER

////////////////// YOU MUST EDIT ONLY HERE ABOUT GLOBAL VARIABLE //////////////////
#define SEGMENT_INDEX         8
#define DIGIT_INDEX           4

#define PODR_DIGIT_MASK       0x01E0
#define PODR_HIGH_MASK        0x7800
#define PODR_LOW_MASK         0x00F0
#define PODR_PIN_MASK         PODR_HIGH_MASK | PODR_LOW_MASK

uint8_t number[10] = {0xC0, 0xF9, 0xA4, 0xB0, 0x99, 0x92, 0x82, 0xD8, 0x80, 0x90};
///////////////////////////////////////////////////////////////////////////////////

uint8_t print_data[4] = {0xFF, 0xFF, 0xFF, 0xFF};

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    Initial_Setting();

    while(true)
        R_FND_Print_Data(print_data);

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

void Initial_Setting()
{
    uint8_t idx = 0;

    for (idx = 1; idx < DIGIT_INDEX + 1; idx++)
        print_data[idx - 1] = number[idx];

    /* 7-Segment LED Pin Output Setting */
    R_PORT3->PCNTR1_b.PDR |= (uint32_t)0x01E0;
    R_PORT6->PCNTR1_b.PDR |= (uint32_t)0x78F0;

    R_FND_Reset();
}

void R_FND_Reset()
{
    /* 7-Segment LED Pin State Initialization */
    R_PORT3->PCNTR1_b.PODR &= ~PODR_DIGIT_MASK & 0xFFFF;
    R_PORT6->PCNTR1_b.PODR |= PODR_PIN_MASK;
}

void R_FND_Print_Data(uint8_t *string)
{
    uint8_t idx = 0;

    if (sizeof(string) != DIGIT_INDEX)
        return;

    for (idx = 0; idx < DIGIT_INDEX; idx++)
        R_FND_Display_Data(idx, string[idx]);
}

void R_FND_Display_Data(uint8_t digit, uint8_t data)
{
    ////////////////// YOU MUST EDIT ONLY HERE ABOUT LOCAL VARIABLE //////////////////



    //////////////////////////////////////////////////////////////////////////////////

    R_BSP_SoftwareDelay(10, BSP_DELAY_UNITS_MICROSECONDS);
    R_FND_Reset();

    ///////////////////// YOU MUST EDIT ONLY HERE ABOUT EXERCISE /////////////////////
    /* 7-Segment Digit Selection */
    R_PORT3->PCNTR1_b.PODR |= (1U << (uint32_t)(digit + 5));

    /* 7-Segment LED Pin State Setting */
    R_PORT6->PCNTR1_b.PODR &= ((uint32_t)(data & 0xF0) << 7U) | ((uint32_t)(data & 0x0F) << 4U);



    //////////////////////////////////////////////////////////////////////////////////
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&g_ioport_ctrl, g_ioport.p_cfg);
    }
}

#if BSP_TZ_SECURE_BUILD

BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
#endif
